# Generated by Django 5.2.7 on 2026-09-08 16:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests_site', '0003_guests_registration_date_recorded'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='guests_registration',
            name='check_out_date',
        ),
        migrations.RemoveField(
            model_name='guests_registration',
            name='number_of_days',
        ),
        migrations.AddField(
            model_name='guests_registration',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='guests_registration',
            name='phone_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='guests_registration',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guests_registration',
            name='check_in_date',
            field=models.DateField(default='2026-09-08'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='guests_registration',
            name='first_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guests_registration',
            name='last_name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='guests_registration',
            name='number_of_nights',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='guests_registration',
            name='room_number',
            field=models.CharField(max_length=10),
        ),
    ]
