# Generated by Django 6.1.1 on 2026-09-28 22:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests_site', '0004_remove_guests_registration_check_out_date_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='guests_registration',
            name='guest_user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='guest_booking', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='guests_registration',
            name='room_type',
            field=models.CharField(choices=[('standard', 'Standard Room'), ('deluxe', 'Deluxe Room'), ('suite', 'Executive Suite')], default='standard', max_length=20),
        ),
        migrations.AlterField(
            model_name='guests_registration',
            name='phone_number',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='guests_registration',
            name='recorded_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_recorded_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='guests_registration',
            name='room_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
